### ISSUE TITLE
More portable version without `realpath`

### ISSUE THREAD

**Issue by kimmoahokas** [chr-fritz/docker-completion.zshplugin#2]
Hey,

I tried using you plugin, but turned out it does not work on recent MacOS versions out of the box because `realpath` is not included in MacOS. I made a fork and fixed that at https://github.com/kimmoahokas/docker-completion.zshplugin

Would you be interested if I created a PR of the change for you?

**Comment by chr-fritz** [comment]
Sounds interessting. Yes it would be great if you can create the PR.

**Comment by kimmoahokas** [comment]
Great, the PR is here: #3


If you have any questions or want me to change anything, let me know. I'm happy to help.
